export function getCountryCode() {
  var timezones = {
    'Europe/Andorra': { country: 'Andorra', iso2: 'AD' },
    'Asia/Dubai': { country: 'United Arab Emirates', iso2: 'AE' },
    'Asia/Kabul': { country: 'Afghanistan', iso2: 'AF' },
    'America/Antigua': { iso2: 'AG', country: 'Antigua & Barbuda' },
    'America/Anguilla': { iso2: 'AI', country: 'Anguilla' },
    'Europe/Tirane': { iso2: 'AL', country: 'Albania' },
    'Asia/Yerevan': { iso2: 'AM', country: 'Armenia' },
    'Africa/Luanda': { iso2: 'AO', country: 'Angola' },
    'Antarctica/Casey': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Davis': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/DumontDUrville': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Mawson': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/McMurdo': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Palmer': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Rothera': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Syowa': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Troll': { iso2: 'AQ', country: 'Antarctica' },
    'Antarctica/Vostok': { iso2: 'AQ', country: 'Antarctica' },
    'America/Argentina/Buenos_Aires': { iso2: 'AR', country: 'Argentina' },
    'America/Buenos_Aires': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Catamarca': { iso2: 'AR', country: 'Argentina' },
    'America/Catamarca': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Cordoba': { iso2: 'AR', country: 'Argentina' },
    'America/Cordoba': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Jujuy': { iso2: 'AR', country: 'Argentina' },
    'America/Jujuy': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/La_Rioja': { iso2: 'AR', country: 'Argentina' },
    'America/La_Rioja': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Mendoza': { iso2: 'AR', country: 'Argentina' },
    'America/Mendoza': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Rio_Gallegos': { iso2: 'AR', country: 'Argentina' },
    'America/Rio_Gallegos': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Salta': { iso2: 'AR', country: 'Argentina' },
    'America/Salta': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/San_Juan': { iso2: 'AR', country: 'Argentina' },
    'America/San_Juan': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/San_Luis': { iso2: 'AR', country: 'Argentina' },
    'America/San_Luis': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Tucuman': { iso2: 'AR', country: 'Argentina' },
    'America/Tucuman': { iso2: 'AR', country: 'Argentina' },
    'America/Argentina/Ushuaia': { iso2: 'AR', country: 'Argentina' },
    'America/Ushuaia': { iso2: 'AR', country: 'Argentina' },
    'Pacific/Pago_Pago': { iso2: 'AS', country: 'American Samoa' },
    'Europe/Vienna': { iso2: 'AT', country: 'Austria' },
    'Antarctica/Macquarie': { iso2: 'AU', country: 'Australia' },
    'Australia/Adelaide': { iso2: 'AU', country: 'Australia' },
    'Australia/Brisbane': { iso2: 'AU', country: 'Australia' },
    'Australia/Broken_Hill': { iso2: 'AU', country: 'Australia' },
    'Australia/Currie': { country: 'Australia', iso2: 'AU' },
    'Australia/Darwin': { country: 'Australia', iso2: 'AU' },
    'Australia/Eucla': { country: 'Australia', iso2: 'AU' },
    'Australia/Hobart': { country: 'Australia', iso2: 'AU' },
    'Australia/Lindeman': { iso2: 'AU', country: 'Australia' },
    'Australia/Lord_Howe': { iso2: 'AU', country: 'Australia' },
    'Australia/Melbourne': { iso2: 'AU', country: 'Australia' },
    'Australia/Perth': { iso2: 'AU', country: 'Australia' },
    'Australia/Sydney': { iso2: 'AU', country: 'Australia' },
    'America/Aruba': { iso2: 'AW', country: 'Aruba' },
    'Europe/Mariehamn': { iso2: 'AX', country: 'Åland Islands' },
    'Asia/Baku': { iso2: 'AZ', country: 'Azerbaijan' },
    'Europe/Sarajevo': { iso2: 'BA', country: 'Bosnia & Herzegovina' },
    'America/Barbados': { iso2: 'BB', country: 'Barbados' },
    'Asia/Dhaka': { iso2: 'BD', country: 'Bangladesh' },
    'Europe/Brussels': { iso2: 'BE', country: 'Belgium' },
    'Africa/Ouagadougou': { iso2: 'BF', country: 'Burkina Faso' },
    'Europe/Sofia': { iso2: 'BG', country: 'Bulgaria' },
    'Asia/Bahrain': { iso2: 'BH', country: 'Bahrain' },
    'Africa/Bujumbura': { iso2: 'BI', country: 'Burundi' },
    'Africa/Porto-Novo': { iso2: 'BJ', country: 'Benin' },
    'America/St_Barthelemy': { iso2: 'BL', country: 'St. Barthélemy' },
    'Atlantic/Bermuda': { iso2: 'BM', country: 'Bermuda' },
    'Asia/Brunei': { iso2: 'BN', country: 'Brunei' },
    'America/La_Paz': { iso2: 'BO', country: 'Bolivia' },
    'America/Kralendijk': { iso2: 'BQ', country: 'Caribbean Netherlands' },
    'America/Araguaina': { iso2: 'BR', country: 'Brazil' },
    'America/Bahia': { iso2: 'BR', country: 'Brazil' },
    'America/Belem': { iso2: 'BR', country: 'Brazil' },
    'America/Boa_Vista': { iso2: 'BR', country: 'Brazil' },
    'America/Campo_Grande': { iso2: 'BR', country: 'Brazil' },
    'America/Cuiaba': { iso2: 'BR', country: 'Brazil' },
    'America/Eirunepe': { iso2: 'BR', country: 'Brazil' },
    'America/Fortaleza': { iso2: 'BR', country: 'Brazil' },
    'America/Maceio': { iso2: 'BR', country: 'Brazil' },
    'America/Manaus': { iso2: 'BR', country: 'Brazil' },
    'America/Noronha': { iso2: 'BR', country: 'Brazil' },
    'America/Porto_Velho': { iso2: 'BR', country: 'Brazil' },
    'America/Recife': { iso2: 'BR', country: 'Brazil' },
    'America/Rio_Branco': { iso2: 'BR', country: 'Brazil' },
    'America/Santarem': { iso2: 'BR', country: 'Brazil' },
    'America/Sao_Paulo': { iso2: 'BR', country: 'Brazil' },
    'America/Nassau': { iso2: 'BS', country: 'Bahamas' },
    'Asia/Thimphu': { iso2: 'BT', country: 'Bhutan' },
    'Africa/Gaborone': { iso2: 'BW', country: 'Botswana' },
    'Europe/Minsk': { iso2: 'BY', country: 'Belarus' },
    'America/Belize': { iso2: 'BZ', country: 'Belize' },
    'America/Atikokan': { iso2: 'CA', country: 'Canada' },
    'America/Blanc-Sablon': { iso2: 'CA', country: 'Canada' },
    'America/Cambridge_Bay': { iso2: 'CA', country: 'Canada' },
    'America/Creston': { iso2: 'CA', country: 'Canada' },
    'America/Dawson': { iso2: 'CA', country: 'Canada' },
    'America/Dawson_Creek': { iso2: 'CA', country: 'Canada' },
    'America/Edmonton': { iso2: 'CA', country: 'Canada' },
    'America/Fort_Nelson': { iso2: 'CA', country: 'Canada' },
    'America/Glace_Bay': { iso2: 'CA', country: 'Canada' },
    'America/Goose_Bay': { iso2: 'CA', country: 'Canada' },
    'America/Halifax': { country: 'Canada', iso2: 'CA' },
    'America/Inuvik': { country: 'Canada', iso2: 'CA' },
    'America/Iqaluit': { country: 'Canada', iso2: 'CA' },
    'America/Moncton': { country: 'Canada', iso2: 'CA' },
    'America/Nipigon': { country: 'Canada', iso2: 'CA' },
    'America/Pangnirtung': { country: 'Canada', iso2: 'CA' },
    'America/Rainy_River': { country: 'Canada', iso2: 'CA' },
    'America/Rankin_Inlet': { country: 'Canada', iso2: 'CA' },
    'America/Regina': { iso2: 'CA', country: 'Canada' },
    'America/Resolute': { iso2: 'CA', country: 'Canada' },
    'America/St_Johns': { iso2: 'CA', country: 'Canada' },
    'America/Swift_Current': { iso2: 'CA', country: 'Canada' },
    'America/Thunder_Bay': { iso2: 'CA', country: 'Canada' },
    'America/Toronto': { iso2: 'CA', country: 'Canada' },
    'America/Vancouver': { iso2: 'CA', country: 'Canada' },
    'America/Whitehorse': { iso2: 'CA', country: 'Canada' },
    'America/Winnipeg': { iso2: 'CA', country: 'Canada' },
    'America/Yellowknife': { iso2: 'CA', country: 'Canada' },
    'Indian/Cocos': { iso2: 'CC', country: 'Cocos (Keeling) Islands' },
    'Africa/Kinshasa': { iso2: 'CD', country: 'Congo - Kinshasa' },
    'Africa/Lubumbashi': { iso2: 'CD', country: 'Congo - Kinshasa' },
    'Africa/Bangui': { iso2: 'CF', country: 'Central African Republic' },
    'Africa/Brazzaville': { iso2: 'CG', country: 'Congo - Brazzaville' },
    'Europe/Zurich': { iso2: 'CH', country: 'Switzerland' },
    'Africa/Abidjan': { iso2: 'CI', country: 'Côte d’Ivoire' },
    'Pacific/Rarotonga': { iso2: 'CK', country: 'Cook Islands' },
    'America/Punta_Arenas': { iso2: 'CL', country: 'Chile' },
    'America/Santiago': { iso2: 'CL', country: 'Chile' },
    'Pacific/Easter': { iso2: 'CL', country: 'Chile' },
    'Africa/Douala': { iso2: 'CM', country: 'Cameroon' },
    'Asia/Shanghai': { iso2: 'CN', country: 'China mainland' },
    'Asia/Urumqi': { iso2: 'CN', country: 'China mainland' },
    'America/Bogota': { iso2: 'CO', country: 'Colombia' },
    'America/Costa_Rica': { iso2: 'CR', country: 'Costa Rica' },
    'America/Havana': { iso2: 'CU', country: 'Cuba' },
    'Atlantic/Cape_Verde': { iso2: 'CV', country: 'Cape Verde' },
    'America/Curacao': { iso2: 'CW', country: 'Curaçao' },
    'Indian/Christmas': { iso2: 'CX', country: 'Christmas Island' },
    'Asia/Famagusta': { iso2: 'CY', country: 'Cyprus' },
    'Asia/Nicosia': { iso2: 'CY', country: 'Cyprus' },
    'Europe/Prague': { iso2: 'CZ', country: 'Czechia' },
    'Europe/Berlin': { iso2: 'DE', country: 'Germany' },
    'Europe/Busingen': { iso2: 'DE', country: 'Germany' },
    'Africa/Djibouti': { iso2: 'DJ', country: 'Djibouti' },
    'Europe/Copenhagen': { iso2: 'DK', country: 'Denmark' },
    'America/Dominica': { iso2: 'DM', country: 'Dominica' },
    'America/Santo_Domingo': { iso2: 'DO', country: 'Dominican Republic' },
    'Africa/Algiers': { iso2: 'DZ', country: 'Algeria' },
    'America/Guayaquil': { country: 'Ecuador', iso2: 'EC' },
    'Pacific/Galapagos': { country: 'Ecuador', iso2: 'EC' },
    'Europe/Tallinn': { country: 'Estonia', iso2: 'EE' },
    'Africa/Cairo': { country: 'Egypt', iso2: 'EG' },
    'Africa/El_Aaiun': { country: 'Western Sahara', iso2: 'EH' },
    'Africa/Asmara': { country: 'Eritrea', iso2: 'ER' },
    'Africa/Ceuta': { country: 'Spain', iso2: 'ES' },
    'Atlantic/Canary': { country: 'Spain', iso2: 'ES' },
    'Europe/Madrid': { country: 'Spain', iso2: 'ES' },
    'Africa/Addis_Ababa': { iso2: 'ET', country: 'Ethiopia' },
    'Europe/Helsinki': { iso2: 'FI', country: 'Finland' },
    'Pacific/Fiji': { iso2: 'FJ', country: 'Fiji' },
    'Atlantic/Stanley': { iso2: 'FK', country: 'Falkland Islands' },
    'Pacific/Chuuk': { iso2: 'FM', country: 'Micronesia' },
    'Pacific/Kosrae': { iso2: 'FM', country: 'Micronesia' },
    'Pacific/Pohnpei': { iso2: 'FM', country: 'Micronesia' },
    'Atlantic/Faroe': { iso2: 'FO', country: 'Faroe Islands' },
    'Europe/Paris': { iso2: 'FR', country: 'France' },
    'Africa/Libreville': { iso2: 'GA', country: 'Gabon' },
    'Europe/London': { iso2: 'GB', country: 'United Kingdom' },
    'America/Grenada': { iso2: 'GD', country: 'Grenada' },
    'Asia/Tbilisi': { iso2: 'GE', country: 'Georgia' },
    'America/Cayenne': { iso2: 'GF', country: 'French Guiana' },
    'Europe/Guernsey': { iso2: 'GG', country: 'Guernsey' },
    'Africa/Accra': { iso2: 'GH', country: 'Ghana' },
    'Europe/Gibraltar': { iso2: 'GI', country: 'Gibraltar' },
    'America/Danmarkshavn': { iso2: 'GL', country: 'Greenland' },
    'America/Godthab': { iso2: 'GL', country: 'Greenland' },
    'America/Scoresbysund': { iso2: 'GL', country: 'Greenland' },
    'America/Thule': { iso2: 'GL', country: 'Greenland' },
    'Africa/Banjul': { iso2: 'GM', country: 'Gambia' },
    'Africa/Conakry': { iso2: 'GN', country: 'Guinea' },
    'America/Guadeloupe': { iso2: 'GP', country: 'Guadeloupe' },
    'Africa/Malabo': { iso2: 'GQ', country: 'Equatorial Guinea' },
    'Europe/Athens': { iso2: 'GR', country: 'Greece' },
    'Atlantic/South_Georgia': { iso2: 'GS', country: 'So. Georgia & So. Sandwich Isl.' },
    'America/Guatemala': { iso2: 'GT', country: 'Guatemala' },
    'Pacific/Guam': { iso2: 'GU', country: 'Guam' },
    'Africa/Bissau': { iso2: 'GW', country: 'Guinea-Bissau' },
    'America/Guyana': { iso2: 'GY', country: 'Guyana' },
    'Asia/Hong_Kong': { iso2: 'HK', country: 'Hong Kong' },
    'America/Tegucigalpa': { iso2: 'HN', country: 'Honduras' },
    'Europe/Zagreb': { iso2: 'HR', country: 'Croatia' },
    'America/Port-au-Prince': { iso2: 'HT', country: 'Haiti' },
    'Europe/Budapest': { iso2: 'HU', country: 'Hungary' },
    'Asia/Jakarta': { iso2: 'ID', country: 'Indonesia' },
    'Asia/Jayapura': { iso2: 'ID', country: 'Indonesia' },
    'Asia/Makassar': { iso2: 'ID', country: 'Indonesia' },
    'Asia/Pontianak': { iso2: 'ID', country: 'Indonesia' },
    'Europe/Dublin': { iso2: 'IE', country: 'Ireland' },
    'Asia/Jerusalem': { iso2: 'IL', country: 'Israel' },
    'Europe/Isle_of_Man': { iso2: 'IM', country: 'Isle of Man' },
    'Asia/Calcutta': { iso2: 'IN', country: 'India' },
    'Asia/Kolkata': { iso2: 'IN', country: 'India' },
    'Indian/Chagos': { iso2: 'IO', country: 'Chagos Archipelago' },
    'Asia/Baghdad': { iso2: 'IQ', country: 'Iraq' },
    'Asia/Tehran': { iso2: 'IR', country: 'Iran' },
    'Atlantic/Reykjavik': { iso2: 'IS', country: 'Iceland' },
    'Europe/Rome': { iso2: 'IT', country: 'Italy' },
    'Europe/Jersey': { iso2: 'JE', country: 'Jersey' },
    'America/Jamaica': { iso2: 'JM', country: 'Jamaica' },
    'Asia/Amman': { iso2: 'JO', country: 'Jordan' },
    'Asia/Tokyo': { iso2: 'JP', country: 'Japan' },
    'Africa/Nairobi': { iso2: 'KE', country: 'Kenya' },
    'Asia/Bishkek': { iso2: 'KG', country: 'Kyrgyzstan' },
    'Asia/Phnom_Penh': { iso2: 'KH', country: 'Cambodia' },
    'Pacific/Enderbury': { iso2: 'KI', country: 'Kiribati' },
    'Pacific/Kiritimati': { iso2: 'KI', country: 'Kiribati' },
    'Pacific/Tarawa': { iso2: 'KI', country: 'Kiribati' },
    'Indian/Comoro': { iso2: 'KM', country: 'Comoros' },
    'America/St_Kitts': { country: 'St. Kitts & Nevis', iso2: 'KN' },
    'Asia/Pyongyang': { country: 'North Korea', iso2: 'KP' },
    'Asia/Seoul': { country: 'South Korea', iso2: 'KR' },
    'Asia/Kuwait': { country: 'Kuwait', iso2: 'KW' },
    'America/Cayman': { country: 'Cayman Islands', iso2: 'KY' },
    'Asia/Almaty': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Aqtau': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Aqtobe': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Atyrau': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Oral': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Qostanay': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Qyzylorda': { country: 'Kazakhstan', iso2: 'KZ' },
    'Asia/Vientiane': { country: 'Laos', iso2: 'LA' },
    'Asia/Beirut': { country: 'Lebanon', iso2: 'LB' },
    'America/St_Lucia': { country: 'St. Lucia', iso2: 'LC' },
    'Europe/Vaduz': { country: 'Liechtenstein', iso2: 'LI' },
    'Asia/Colombo': { country: 'Sri Lanka', iso2: 'LK' },
    'Africa/Monrovia': { country: 'Liberia', iso2: 'LR' },
    'Africa/Maseru': { country: 'Lesotho', iso2: 'LS' },
    'Europe/Vilnius': { country: 'Lithuania', iso2: 'LT' },
    'Europe/Luxembourg': { country: 'Luxembourg', iso2: 'LU' },
    'Europe/Riga': { country: 'Latvia', iso2: 'LV' },
    'Africa/Tripoli': { country: 'Libya', iso2: 'LY' },
    'Africa/Casablanca': { country: 'Morocco', iso2: 'MA' },
    'Europe/Monaco': { country: 'Monaco', iso2: 'MC' },
    'Europe/Chisinau': { country: 'Moldova', iso2: 'MD' },
    'Europe/Podgorica': { country: 'Montenegro', iso2: 'ME' },
    'America/Marigot': { country: 'St. Martin', iso2: 'MF' },
    'Indian/Antananarivo': { country: 'Madagascar', iso2: 'MG' },
    'Pacific/Kwajalein': { country: 'Marshall Islands', iso2: 'MH' },
    'Pacific/Majuro': { country: 'Marshall Islands', iso2: 'MH' },
    'Europe/Skopje': { country: 'North Macedonia', iso2: 'MK' },
    'Africa/Bamako': { country: 'Mali', iso2: 'ML' },
    'Asia/Yangon': { country: 'Myanmar (Burma)', iso2: 'MM' },
    'Asia/Choibalsan': { country: 'Mongolia', iso2: 'MN' },
    'Asia/Hovd': { country: 'Mongolia', iso2: 'MN' },
    'Asia/Ulaanbaatar': { country: 'Mongolia', iso2: 'MN' },
    'Asia/Macau': { country: 'Macao', iso2: 'MO' },
    'Pacific/Saipan': { country: 'Northern Mariana Islands', iso2: 'MP' },
    'America/Martinique': { country: 'Martinique', iso2: 'MQ' },
    'Africa/Nouakchott': { country: 'Mauritania', iso2: 'MR' },
    'America/Montserrat': { country: 'Montserrat', iso2: 'MS' },
    'Europe/Malta': { country: 'Malta', iso2: 'MT' },
    'Indian/Mauritius': { country: 'Mauritius', iso2: 'MU' },
    'Indian/Maldives': { country: 'Maldives', iso2: 'MV' },
    'Africa/Blantyre': { country: 'Malawi', iso2: 'MW' },
    'America/Bahia_Banderas': { country: 'Mexico', iso2: 'MX' },
    'America/Cancun': { country: 'Mexico', iso2: 'MX' },
    'America/Chihuahua': { country: 'Mexico', iso2: 'MX' },
    'America/Hermosillo': { country: 'Mexico', iso2: 'MX' },
    'America/Matamoros': { country: 'Mexico', iso2: 'MX' },
    'America/Mazatlan': { country: 'Mexico', iso2: 'MX' },
    'America/Merida': { country: 'Mexico', iso2: 'MX' },
    'America/Mexico_City': { country: 'Mexico', iso2: 'MX' },
    'America/Monterrey': { country: 'Mexico', iso2: 'MX' },
    'America/Ojinaga': { country: 'Mexico', iso2: 'MX' },
    'America/Tijuana': { country: 'Mexico', iso2: 'MX' },
    'Asia/Kuala_Lumpur': { country: 'Malaysia', iso2: 'MY' },
    'Asia/Kuching': { country: 'Malaysia', iso2: 'MY' },
    'Africa/Maputo': { country: 'Mozambique', iso2: 'MZ' },
    'Africa/Windhoek': { country: 'Namibia', iso2: 'NA' },
    'Pacific/Noumea': { country: 'New Caledonia', iso2: 'NC' },
    'Africa/Niamey': { country: 'Niger', iso2: 'NE' },
    'Pacific/Norfolk': { country: 'Norfolk Island', iso2: 'NF' },
    'Africa/Lagos': { country: 'Nigeria', iso2: 'NG' },
    'America/Managua': { country: 'Nicaragua', iso2: 'NI' },
    'Europe/Amsterdam': { country: 'Netherlands', iso2: 'NL' },
    'Europe/Oslo': { country: 'Norway', iso2: 'NO' },
    'Asia/Kathmandu': { country: 'Nepal', iso2: 'NP' },
    'Pacific/Nauru': { country: 'Nauru', iso2: 'NR' },
    'Pacific/Niue': { country: 'Niue', iso2: 'NU' },
    'Pacific/Auckland': { country: 'New Zealand', iso2: 'NZ' },
    'Pacific/Chatham': { country: 'New Zealand', iso2: 'NZ' },
    'Asia/Muscat': { country: 'Oman', iso2: 'OM' },
    'America/Panama': { country: 'Panama', iso2: 'PA' },
    'America/Lima': { iso2: 'PE', country: 'Peru' },
    'Pacific/Gambier': { country: 'French Polynesia', iso2: 'PF' },
    'Pacific/Marquesas': { country: 'French Polynesia', iso2: 'PF' },
    'Pacific/Tahiti': { country: 'French Polynesia', iso2: 'PF' },
    'Pacific/Bougainville': { country: 'Papua New Guinea', iso2: 'PG' },
    'Pacific/Port_Moresby': { country: 'Papua New Guinea', iso2: 'PG' },
    'Asia/Manila': { country: 'Philippines', iso2: 'PH' },
    'Asia/Karachi': { country: 'Pakistan', iso2: 'PK' },
    'Europe/Warsaw': { country: 'Poland', iso2: 'PL' },
    'America/Miquelon': { country: 'St. Pierre & Miquelon', iso2: 'PM' },
    'Pacific/Pitcairn': { country: 'Pitcairn Islands', iso2: 'PN' },
    'America/Puerto_Rico': { country: 'Puerto Rico', iso2: 'PR' },
    'Asia/Gaza': { country: 'Palestinian Territories', iso2: 'PS' },
    'Asia/Hebron': { country: 'Palestinian Territories', iso2: 'PS' },
    'Atlantic/Azores': { country: 'Portugal', iso2: 'PT' },
    'Atlantic/Madeira': { country: 'Portugal', iso2: 'PT' },
    'Europe/Lisbon': { country: 'Portugal', iso2: 'PT' },
    'Pacific/Palau': { country: 'Palau', iso2: 'PW' },
    'America/Asuncion': { country: 'Paraguay', iso2: 'PY' },
    'Asia/Qatar': { country: 'Qatar', iso2: 'QA' },
    'Indian/Reunion': { country: 'Réunion', iso2: 'RE' },
    'Europe/Bucharest': { country: 'Romania', iso2: 'RO' },
    'Europe/Belgrade': { country: 'Serbia', iso2: 'RS' },
    'Asia/Anadyr': { country: 'Russia', iso2: 'RU' },
    'Asia/Barnaul': { country: 'Russia', iso2: 'RU' },
    'Asia/Chita': { country: 'Russia', iso2: 'RU' },
    'Asia/Irkutsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Kamchatka': { country: 'Russia', iso2: 'RU' },
    'Asia/Khandyga': { country: 'Russia', iso2: 'RU' },
    'Asia/Krasnoyarsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Magadan': { country: 'Russia', iso2: 'RU' },
    'Asia/Novokuznetsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Novosibirsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Omsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Sakhalin': { country: 'Russia', iso2: 'RU' },
    'Asia/Srednekolymsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Tomsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Ust-Nera': { country: 'Russia', iso2: 'RU' },
    'Asia/Vladivostok': { country: 'Russia', iso2: 'RU' },
    'Asia/Yakutsk': { country: 'Russia', iso2: 'RU' },
    'Asia/Yekaterinburg': { country: 'Russia', iso2: 'RU' },
    'Europe/Astrakhan': { country: 'Russia', iso2: 'RU' },
    'Europe/Kaliningrad': { country: 'Russia', iso2: 'RU' },
    'Europe/Kirov': { country: 'Russia', iso2: 'RU' },
    'Europe/Moscow': { country: 'Russia', iso2: 'RU' },
    'Europe/Samara': { country: 'Russia', iso2: 'RU' },
    'Europe/Saratov': { country: 'Russia', iso2: 'RU' },
    'Europe/Ulyanovsk': { country: 'Russia', iso2: 'RU' },
    'Europe/Volgograd': { country: 'Russia', iso2: 'RU' },
    'Africa/Kigali': { country: 'Rwanda', iso2: 'RW' },
    'Asia/Riyadh': { country: 'Saudi Arabia', iso2: 'SA' },
    'Pacific/Guadalcanal': { country: 'Solomon Islands', iso2: 'SB' },
    'Indian/Mahe': { country: 'Seychelles', iso2: 'SC' },
    'Africa/Khartoum': { country: 'Sudan', iso2: 'SD' },
    'Europe/Stockholm': { country: 'Sweden', iso2: 'SE' },
    'Asia/Singapore': { country: 'Singapore', iso2: 'SG' },
    'Atlantic/St_Helena': { country: 'St. Helena', iso2: 'SH' },
    'Europe/Ljubljana': { country: 'Slovenia', iso2: 'SI' },
    'Arctic/Longyearbyen': { country: 'Svalbard & Jan Mayen', iso2: 'SJ' },
    'Europe/Bratislava': { country: 'Slovakia', iso2: 'SK' },
    'Africa/Freetown': { country: 'Sierra Leone', iso2: 'SL' },
    'Europe/San_Marino': { country: 'San Marino', iso2: 'SM' },
    'Africa/Dakar': { country: 'Senegal', iso2: 'SN' },
    'Africa/Mogadishu': { country: 'Somalia', iso2: 'SO' },
    'America/Paramaribo': { country: 'Suriname', iso2: 'SR' },
    'Africa/Juba': { country: 'South Sudan', iso2: 'SS' },
    'Africa/Sao_Tome': { country: 'São Tomé & Príncipe', iso2: 'ST' },
    'America/El_Salvador': { country: 'El Salvador', iso2: 'SV' },
    'America/Lower_Princes': { country: 'Sint Maarten', iso2: 'SX' },
    'Asia/Damascus': { country: 'Syria', iso2: 'SY' },
    'Africa/Mbabane': { country: 'Eswatini', iso2: 'SZ' },
    'America/Grand_Turk': { country: 'Turks & Caicos Islands', iso2: 'TC' },
    'Africa/Ndjamena': { country: 'Chad', iso2: 'TD' },
    'Indian/Kerguelen': { country: 'French Southern Territories', iso2: 'TF' },
    'Africa/Lome': { country: 'Togo', iso2: 'TG' },
    'Asia/Bangkok': { country: 'Thailand', iso2: 'TH' },
    'Asia/Dushanbe': { country: 'Tajikistan', iso2: 'TJ' },
    'Pacific/Fakaofo': { country: 'Tokelau', iso2: 'TK' },
    'Asia/Dili': { country: 'Timor-Leste', iso2: 'TL' },
    'Asia/Ashgabat': { country: 'Turkmenistan', iso2: 'TM' },
    'Africa/Tunis': { country: 'Tunisia', iso2: 'TN' },
    'Pacific/Tongatapu': { country: 'Tonga', iso2: 'TO' },
    'Europe/Istanbul': { country: 'Turkey', iso2: 'TR' },
    'America/Port_of_Spain': { country: 'Trinidad & Tobago', iso2: 'TT' },
    'Pacific/Funafuti': { country: 'Tuvalu', iso2: 'TV' },
    'Asia/Taipei': { country: 'Taiwan', iso2: 'TW' },
    'Africa/Dar_es_Salaam': { country: 'Tanzania', iso2: 'TZ' },
    'Europe/Kiev': { country: 'Ukraine', iso2: 'UA' },
    'Europe/Simferopol': { country: 'Ukraine', iso2: 'UA' },
    'Europe/Uzhgorod': { country: 'Ukraine', iso2: 'UA' },
    'Europe/Zaporozhye': { country: 'Ukraine', iso2: 'UA' },
    'Africa/Kampala': { country: 'Uganda', iso2: 'UG' },
    'Pacific/Midway': { country: 'U.S. Outlying Islands', iso2: 'UM' },
    'Pacific/Wake': { country: 'U.S. Outlying Islands', iso2: 'UM' },
    'America/Adak': { country: 'United States', iso2: 'US' },
    'America/Anchorage': { country: 'United States', iso2: 'US' },
    'America/Boise': { country: 'United States', iso2: 'US' },
    'America/Chicago': { country: 'United States', iso2: 'US' },
    'America/Denver': { country: 'United States', iso2: 'US' },
    'America/Detroit': { country: 'United States', iso2: 'US' },
    'America/Indiana/Indianapolis': { country: 'United States', iso2: 'US' },
    'America/Indianapolis': { country: 'United States', iso2: 'US' },
    'America/Indiana/Knox': { country: 'United States', iso2: 'US' },
    'America/Knox': { country: 'United States', iso2: 'US' },
    'America/Indiana/Marengo': { country: 'United States', iso2: 'US' },
    'America/Marengo': { country: 'United States', iso2: 'US' },
    'America/Indiana/Petersburg': { country: 'United States', iso2: 'US' },
    'America/Petersburg': { country: 'United States', iso2: 'US' },
    'America/Indiana/Tell_City': { country: 'United States', iso2: 'US' },
    'America/Tell_City': { country: 'United States', iso2: 'US' },
    'America/Indiana/Vevay': { country: 'United States', iso2: 'US' },
    'America/Vevay': { country: 'United States', iso2: 'US' },
    'America/Indiana/Vincennes': { country: 'United States', iso2: 'US' },
    'America/Vincennes': { country: 'United States', iso2: 'US' },
    'America/Indiana/Winamac': { country: 'United States', iso2: 'US' },
    'America/Winamac': { country: 'United States', iso2: 'US' },
    'America/Juneau': { country: 'United States', iso2: 'US' },
    'America/Kentucky/Louisville': { country: 'United States', iso2: 'US' },
    'America/Louisville': { country: 'United States', iso2: 'US' },
    'America/Kentucky/Monticello': { country: 'United States', iso2: 'US' },
    'America/Monticello': { country: 'United States', iso2: 'US' },
    'America/Los_Angeles': { country: 'United States', iso2: 'US' },
    'America/Menominee': { country: 'United States', iso2: 'US' },
    'America/Metlakatla': { country: 'United States', iso2: 'US' },
    'America/New_York': { country: 'United States', iso2: 'US' },
    'America/Nome': { country: 'United States', iso2: 'US' },
    'America/North_Dakota/Beulah': { country: 'United States', iso2: 'US' },
    'America/Beulah': { country: 'United States', iso2: 'US' },
    'America/North_Dakota/Center': { country: 'United States', iso2: 'US' },
    'America/Center': { country: 'United States', iso2: 'US' },
    'America/North_Dakota/New_Salem': { country: 'United States', iso2: 'US' },
    'America/New_Salem': { country: 'United States', iso2: 'US' },
    'America/Phoenix': { country: 'United States', iso2: 'US' },
    'America/Sitka': { country: 'United States', iso2: 'US' },
    'America/Yakutat': { country: 'United States', iso2: 'US' },
    'Pacific/Honolulu': { country: 'United States', iso2: 'US' },
    'America/Montevideo': { country: 'Uruguay', iso2: 'UY' },
    'Asia/Samarkand': { country: 'Uzbekistan', iso2: 'UZ' },
    'Asia/Tashkent': { country: 'Uzbekistan', iso2: 'UZ' },
    'Europe/Vatican': { country: 'Vatican City', iso2: 'VA' },
    'America/St_Vincent': { country: 'St. Vincent & Grenadines', iso2: 'VC' },
    'America/Caracas': { country: 'Venezuela', iso2: 'VE' },
    'America/Tortola': { country: 'British Virgin Islands', iso2: 'VG' },
    'America/St_Thomas': { country: 'U.S. Virgin Islands', iso2: 'VI' },
    'Asia/Ho_Chi_Minh': { country: 'Vietnam', iso2: 'VN' },
    'Pacific/Efate': { country: 'Vanuatu', iso2: 'VU' },
    'Pacific/Wallis': { country: 'Wallis & Futuna', iso2: 'WF' },
    'Pacific/Apia': { country: 'Samoa', iso2: 'WS' },
    'Asia/Aden': { country: 'Yemen', iso2: 'YE' },
    'Indian/Mayotte': { country: 'Mayotte', iso2: 'YT' },
    'Africa/Johannesburg': { country: 'South Africa', iso2: 'ZA' },
    'Africa/Lusaka': { country: 'Zambia', iso2: 'ZM' },
    'Africa/Harare': { country: 'Zimbabwe', iso2: 'ZW' }
  };
  const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
  if (timezone === '' || !timezone) {
    return 'US';
  }
  const country = timezones[timezone];
  if (!country) {
    return 'US';
  }
  return country.iso2;
}
